### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by orthagh** [glpi-project/telemetry#63]
just to distinguish this site in my 20k opened tabs, please !!!

**Comment by trasher** [comment]
Provide an image and I'll add it :p

**Comment by trasher** [comment]
Just checked... In facts, it's already been done:
https://github.com/glpi-project/telemetry/commit/a860e08603673940cb0a7612a96f57eeb72441dc

You just have to put in place a favicon.png file and you're done (see https://telemetry.galette.eu/)
